<?php

return [
    'store-sales' => [
        'REFERENCE NUMBER',
        'SYSTEM',
        'ORG',
        'REPORT TYPE',
        'CHANNEL CODE',
        'CUSTOMER LOCATION',
        'RECEIPT NUMBER',
        'SOLD DATE',
        'ITEM NUMBER',
        'RR REF',
        'ITEM DESCRIPTION',
        'QTY SOLD',
        'SOLD PRICE',
        'NET SALES',
        'STORE COST',
        'STORE COST ECOMM',
        'LANDED COST',
        'SALE MEMO REF',
        'ITEM SERIAL',
        'SALES PERSON'
    ],

    'gashapon-store-sales' => [
        'REFERENCE NUMBER',
        'SYSTEM',
        'ORG',
        'REPORT TYPE',
        'CHANNEL CODE',
        'CUSTOMER LOCATION',
        'RECEIPT NUMBER',
        'SOLD DATE',
        'ITEM NUMBER',
        'RR REF',
        'ITEM DESCRIPTION',
        'QTY SOLD',
        'SOLD PRICE',
        'NET SALES',
        'STORE COST',
        'STORE COST ECOMM',
        'LANDED COST',
        'SALE MEMO REF'
    ],

    'store-inventory' => [
        'REFERENCE NUMBER',
        'SYSTEM',
        'ORG',
        'REPORT TYPE',
        'CHANNEL CODE',
        'SUB INVENTORY',
        'CUSTOMER LOCATION',
        'INVENTORY AS OF DATE',
        'ITEM NUMBER',
        'ITEM DESCRIPTION',
        'INVENTORY QTY',
        'STORE COST',
        'STORE COST ECOMM',
        'LANDED COST',
        'PRODUCT QUALITY'
    ],

    'supplier-intransit-inventory' => [
        'REFERENCE NUMBER',
        'SYSTEM',
        'ORG',
        'REPORT TYPE',
        'CHANNEL CODE',
        'SUB INVENTORY',
        'CUSTOMER LOCATION',
        'INVENTORY AS OF DATE',
        'ITEM NUMBER',
        'ITEM DESCRIPTION',
        'INVENTORY QTY',
        'STORE COST',
        'STORE COST ECOMM',
        'LANDED COST',
        'PRODUCT QUALITY'
    ],

    'digits-sales' => [
        'REFERENCE NUMBER',
        'SYSTEM',
        'ORG',
        'REPORT TYPE',
        'CHANNEL CODE',
        'CUSTOMER BILL TO',
        'BILL TO',
        'RECEIPT NUMBER',
        'SOLD DATE',
        'ITEM NUMBER',
        'RR REF',
        'ITEM DESCRIPTION',
        'QTY SOLD',
        'SOLD PRICE',
        'NET SALES',
        'STORE COST',
        'STORE COST ECOMM',
        'LANDED COST',
        'SALE MEMO REF'
    ],

    'warehouse-inventory' => [
        'REFERENCE NUMBER',
        'SYSTEM',
        'ORG',
        'REPORT TYPE',
        'CHANNEL CODE',
        'SUB INVENTORY',
        'CUSTOMER LOCATION',
        'INVENTORY AS OF DATE',
        'ITEM NUMBER',
        'ITEM DESCRIPTION',
        'INVENTORY QTY',
        'STORE COST',
        'STORE COST ECOMM',
        'LANDED COST',
        'PRODUCT QUALITY'
    ],
];

?>
